import type { Metadata } from "next"


export const metadata:Metadata = {
    title: 'Nosotros',
    description: 'Generated by create next app',
}
export default function AboutPage() {
  return (
    <main className="">
      <span className="text-7xl">page</span >
    </main>
  )
}
